#!/bin/sh
case "$LEONOS_BOOT_MODE" in
    tty) exec /sbin/getty -L -n -l /usr/lib/leonos/apps/login/login.elf 115200 - xterm-256color ;;
    installer-tty)
        test -f /etc/leonos/installer-runtime || exit 1
        exec /usr/lib/leonos/apps/installer/installer.elf ;;
    *) # GUI owns keyboard input; keep BusyBox's respawn child quiescent.
        exec /bin/sleep 2147483647 ;;
esac
