/* Transitional compatibility forwarder (ReliefOS / ReliefNT rename).
 * Canonical declarations: <reliefos/app.h>.
 * No second layout definition exists behind these names. */
#ifndef LEONOS_APP_H
#define LEONOS_APP_H
#include <reliefos/app.h>

/* Old names alias the single canonical declaration. */
#define LEONOS_APP_CATEGORY_LEN RELIEFOS_APP_CATEGORY_LEN
#define LEONOS_APP_FLAG_ENTRY RELIEFOS_APP_FLAG_ENTRY
#define LEONOS_APP_FLAG_HIDDEN RELIEFOS_APP_FLAG_HIDDEN
#define LEONOS_APP_FLAG_OPEN_WITH RELIEFOS_APP_FLAG_OPEN_WITH
#define LEONOS_APP_FLAG_SYSTEM RELIEFOS_APP_FLAG_SYSTEM
#define LEONOS_APP_FLAG_TERMINAL RELIEFOS_APP_FLAG_TERMINAL
#define LEONOS_APP_ID_LEN RELIEFOS_APP_ID_LEN
#define LEONOS_APP_LIST_LEN RELIEFOS_APP_LIST_LEN
#define LEONOS_APP_NAME_LEN RELIEFOS_APP_NAME_LEN
#define LEONOS_APP_PATH_LEN RELIEFOS_APP_PATH_LEN
#define LEONOS_APP_REGISTRY_MAX RELIEFOS_APP_REGISTRY_MAX
#define LEONOS_APP_VERSION_LEN RELIEFOS_APP_VERSION_LEN
#define leonos_app_info reliefos_app_info
#define leonos_app_registry_begin_refresh reliefos_app_registry_begin_refresh
#define leonos_app_registry_count reliefos_app_registry_count
#define leonos_app_registry_default_for_extension reliefos_app_registry_default_for_extension
#define leonos_app_registry_find reliefos_app_registry_find
#define leonos_app_registry_get reliefos_app_registry_get
#define leonos_app_registry_icon reliefos_app_registry_icon
#define leonos_app_registry_is_loaded reliefos_app_registry_is_loaded
#define leonos_app_registry_is_loading reliefos_app_registry_is_loading
#define leonos_app_registry_label reliefos_app_registry_label
#define leonos_app_registry_refresh reliefos_app_registry_refresh
#define leonos_app_registry_refresh_step reliefos_app_registry_refresh_step
#define leonos_app_registry_resolve reliefos_app_registry_resolve
#endif /* LEONOS_APP_H */
