/* Transitional compatibility forwarder (ReliefOS / ReliefNT rename).
 * Canonical declarations: <reliefos/launch.h>.
 * No second layout definition exists behind these names. */
#ifndef LEONOS_LAUNCH_H
#define LEONOS_LAUNCH_H
#include <reliefos/launch.h>

/* Old names alias the single canonical declaration. */
#define LEONOS_LAUNCH_ASSOC_COUNT RELIEFOS_LAUNCH_ASSOC_COUNT
#define LEONOS_LAUNCH_ASSOC_MODE_EXEC RELIEFOS_LAUNCH_ASSOC_MODE_EXEC
#define LEONOS_LAUNCH_ASSOC_MODE_OPEN_TEXT RELIEFOS_LAUNCH_ASSOC_MODE_OPEN_TEXT
#define LEONOS_LAUNCH_ASSOC_MODE_TERMINAL_CAT RELIEFOS_LAUNCH_ASSOC_MODE_TERMINAL_CAT
#define LEONOS_LAUNCH_ERR_ALREADY_RUNNING RELIEFOS_LAUNCH_ERR_ALREADY_RUNNING
#define LEONOS_LAUNCH_ERR_EMPTY RELIEFOS_LAUNCH_ERR_EMPTY
#define LEONOS_LAUNCH_ERR_EXISTS RELIEFOS_LAUNCH_ERR_EXISTS
#define LEONOS_LAUNCH_ERR_INVALID_SHORTCUT RELIEFOS_LAUNCH_ERR_INVALID_SHORTCUT
#define LEONOS_LAUNCH_ERR_NOT_FOUND RELIEFOS_LAUNCH_ERR_NOT_FOUND
#define LEONOS_LAUNCH_ERR_NO_ASSOCIATION RELIEFOS_LAUNCH_ERR_NO_ASSOCIATION
#define LEONOS_LAUNCH_ERR_SHORTCUT_LOOP RELIEFOS_LAUNCH_ERR_SHORTCUT_LOOP
#define LEONOS_LAUNCH_ERR_TOO_MANY_ARGS RELIEFOS_LAUNCH_ERR_TOO_MANY_ARGS
#define LEONOS_LAUNCH_ERR_UNCLOSED_QUOTE RELIEFOS_LAUNCH_ERR_UNCLOSED_QUOTE
#define LEONOS_LAUNCH_MAX_ARGS RELIEFOS_LAUNCH_MAX_ARGS
#define leonos_cmdline_split reliefos_cmdline_split
#define leonos_launch_argv reliefos_launch_argv
#define leonos_launch_assoc_app reliefos_launch_assoc_app
#define leonos_launch_assoc_apps reliefos_launch_assoc_apps
#define leonos_launch_builtin_path reliefos_launch_builtin_path
#define leonos_launch_command_line reliefos_launch_command_line
#define leonos_launch_create_shortcut reliefos_launch_create_shortcut
#define leonos_launch_create_shortcut_in_dir reliefos_launch_create_shortcut_in_dir
#define leonos_launch_default_shortcut_name reliefos_launch_default_shortcut_name
#define leonos_launch_error_text reliefos_launch_error_text
#define leonos_launch_file_with_app reliefos_launch_file_with_app
#define leonos_launch_get_extension_association reliefos_launch_get_extension_association
#define leonos_launch_get_extension_for_path reliefos_launch_get_extension_for_path
#define leonos_launch_resolve_default_app_for_path reliefos_launch_resolve_default_app_for_path
#define leonos_launch_set_extension_association reliefos_launch_set_extension_association
#define leonos_launch_use_session reliefos_launch_use_session
#define leonos_spawn_argv reliefos_spawn_argv
#endif /* LEONOS_LAUNCH_H */
