#!/usr/bin/env python3
"""Regenerate the checked-in component Kconfig from configs/components.toml."""

from __future__ import annotations

import argparse
import re
import sys
import tomllib
from collections import defaultdict
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]


def quote(value: str) -> str:
    return value.replace("\\", "\\\\").replace('"', '\\"')


def load_components(path: Path) -> tuple[dict[str, object], ...]:
    try:
        data = tomllib.loads(path.read_text(encoding="utf-8"))
    except (OSError, tomllib.TOMLDecodeError) as exc:
        raise ValueError(f"cannot read component manifest {path}: {exc}") from exc
    if data.get("version") != 1 or not isinstance(data.get("components"), list):
        raise ValueError("manifest must use schema version 1 and define components")
    components = tuple(data["components"])
    if not components:
        raise ValueError("manifest has no components")
    ids: set[str] = set()
    symbols: set[str] = set()
    for component in components:
        if not isinstance(component, dict):
            raise ValueError("each component must be a table")
        component_id = component.get("id")
        symbol = component.get("symbol")
        if not isinstance(component_id, str) or not re.fullmatch(r"[a-z][a-z0-9_-]*", component_id):
            raise ValueError(f"invalid component id: {component_id!r}")
        if not isinstance(symbol, str) or not re.fullmatch(r"[A-Z][A-Z0-9_]*", symbol):
            raise ValueError(f"invalid component symbol for {component_id}")
        if component_id in ids or symbol in symbols:
            raise ValueError(f"duplicate component id or symbol: {component_id}/{symbol}")
        ids.add(component_id)
        symbols.add(symbol)
        for field in ("label", "category"):
            if not isinstance(component.get(field), str) or not component[field]:
                raise ValueError(f"component {component_id} needs {field}")
        for field in ("default", "required", "stage", "entry", "sdk", "api"):
            if not isinstance(component.get(field), bool):
                raise ValueError(f"component {component_id} needs boolean {field}")
        dependencies = component.get("depends", [])
        if not isinstance(dependencies, list) or any(not isinstance(dep, str) for dep in dependencies):
            raise ValueError(f"component {component_id} has invalid dependencies")
    for component in components:
        for dependency in component.get("depends", []):
            if dependency not in ids:
                raise ValueError(f"component {component['id']} depends on unknown {dependency}")
    return components


def symbol(component: dict[str, object], suffix: str) -> str:
    return f"RELIEFOS_COMPONENT_{component['symbol']}_{suffix}"


def generate(components: tuple[dict[str, object], ...]) -> str:
    by_id = {str(component["id"]): component for component in components}
    categories: dict[str, list[dict[str, object]]] = defaultdict(list)
    for component in components:
        if not component["required"]:
            categories[str(component["category"])].append(component)
    lines = [
        "# This file is generated by tools/generate_component_kconfig.py.",
        "# Edit configs/components.toml instead.",
        "",
    ]
    for category in sorted(categories):
        lines.extend([f'menu "{quote(category)}"', ""])
        for component in categories[category]:
            label = quote(str(component["label"]))
            build = symbol(component, "BUILD")
            lines.extend([
                f"config {build}",
                f'    bool "Build {label}"',
                f"    default {'y' if component['default'] else 'n'}",
            ])
            for dependency in component.get("depends", []):
                dependency_component = by_id[str(dependency)]
                if not dependency_component["required"]:
                    lines.append(f"    select {symbol(dependency_component, 'BUILD')}")
            lines.append("")
            option_specs = [
                ("IMAGE", component["stage"], f"Include {label} in system images"),
                ("ENTRY", component["entry"], f"Generate a desktop entry for {label}"),
                ("SDK", component["sdk"], f"Include {label} in the developer SDK"),
            ]
            if component["api"] and component.get("api_stage_path"):
                option_specs.append(("API", True, f"Build the API package for {label}"))
            for suffix, default, prompt in option_specs:
                lines.extend([
                    f"config {symbol(component, suffix)}",
                    f'    bool "{prompt}"',
                    f"    default {'y' if default else 'n'}",
                    f"    depends on {build}",
                    "",
                ])
        lines.extend(["endmenu", ""])
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--manifest", default="configs/components.toml")
    parser.add_argument("--output", default="Kconfig.components")
    args = parser.parse_args()
    try:
        output = ROOT / args.output
        generated = generate(load_components(ROOT / args.manifest))
        if not output.exists() or output.read_text(encoding="utf-8") != generated:
            output.write_text(generated, encoding="utf-8", newline="\n")
    except (OSError, ValueError) as exc:
        print(f"component Kconfig: {exc}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
