/* Transitional compatibility forwarder (ReliefOS / ReliefNT rename).
 * Canonical declarations: <reliefos/api.h>.
 * No second layout definition exists behind these names. */
#ifndef LEONOS_API_H
#define LEONOS_API_H
#include <reliefos/api.h>

/* Old names alias the single canonical declaration. */
#define LEONOS_API_NAME_LEN RELIEFOS_API_NAME_LEN
#define LEONOS_API_PATH_MAX RELIEFOS_API_PATH_MAX
#define LEONOS_API_VERSION_LEN RELIEFOS_API_VERSION_LEN
#define LEONOS_INPUTM_ABBREV_LEN RELIEFOS_INPUTM_ABBREV_LEN
#define LEONOS_INPUTM_CONTEXT_FOCUSED RELIEFOS_INPUTM_CONTEXT_FOCUSED
#define LEONOS_INPUTM_CONTEXT_SECURE RELIEFOS_INPUTM_CONTEXT_SECURE
#define LEONOS_INPUTM_H RELIEFOS_INPUTM_H
#define LEONOS_INPUTM_ID_LEN RELIEFOS_INPUTM_ID_LEN
#define LEONOS_INPUTM_MAX_CANDIDATES RELIEFOS_INPUTM_MAX_CANDIDATES
#define LEONOS_INPUTM_MAX_PROVIDERS RELIEFOS_INPUTM_MAX_PROVIDERS
#define LEONOS_INPUTM_NAME_LEN RELIEFOS_INPUTM_NAME_LEN
#define LEONOS_INPUTM_RENDER_CONTROLS RELIEFOS_INPUTM_RENDER_CONTROLS
#define LEONOS_INPUTM_RENDER_PIXELS RELIEFOS_INPUTM_RENDER_PIXELS
#define LEONOS_INPUTM_RESULT_CANCEL RELIEFOS_INPUTM_RESULT_CANCEL
#define LEONOS_INPUTM_RESULT_COMMIT RELIEFOS_INPUTM_RESULT_COMMIT
#define LEONOS_INPUTM_RESULT_COMPOSITION RELIEFOS_INPUTM_RESULT_COMPOSITION
#define LEONOS_INPUTM_RESULT_PASSTHROUGH RELIEFOS_INPUTM_RESULT_PASSTHROUGH
#define LEONOS_INPUTM_START_LOGIN RELIEFOS_INPUTM_START_LOGIN
#define LEONOS_INPUTM_START_MANUAL RELIEFOS_INPUTM_START_MANUAL
#define LEONOS_INPUTM_START_ON_DEMAND RELIEFOS_INPUTM_START_ON_DEMAND
#define LEONOS_INPUTM_TEXT_LEN RELIEFOS_INPUTM_TEXT_LEN
#define LEONOS_UAPI_INPUTM_ABI_H RELIEFOS_UAPI_INPUTM_ABI_H
#define leonos_api_extract_files reliefos_api_extract_files
#define leonos_api_info reliefos_api_info
#define leonos_api_install reliefos_api_install
#define leonos_api_install_with_progress reliefos_api_install_with_progress
#define leonos_api_parse_info reliefos_api_parse_info
#define leonos_api_progress_fn reliefos_api_progress_fn
#define leonos_inputm_active_request reliefos_inputm_active_request
#define leonos_inputm_config_request reliefos_inputm_config_request
#define leonos_inputm_context reliefos_inputm_context
#define leonos_inputm_get_state reliefos_inputm_get_state
#define leonos_inputm_key_event reliefos_inputm_key_event
#define leonos_inputm_list reliefos_inputm_list
#define leonos_inputm_note_gui_window reliefos_inputm_note_gui_window
#define leonos_inputm_notify_config reliefos_inputm_notify_config
#define leonos_inputm_observe_gui_key reliefos_inputm_observe_gui_key
#define leonos_inputm_poll_gui_commit reliefos_inputm_poll_gui_commit
#define leonos_inputm_poll_result reliefos_inputm_poll_result
#define leonos_inputm_provider reliefos_inputm_provider
#define leonos_inputm_provider_list reliefos_inputm_provider_list
#define leonos_inputm_provider_next reliefos_inputm_provider_next
#define leonos_inputm_provider_result reliefos_inputm_provider_result
#define leonos_inputm_register reliefos_inputm_register
#define leonos_inputm_result reliefos_inputm_result
#define leonos_inputm_set_active reliefos_inputm_set_active
#define leonos_inputm_set_context reliefos_inputm_set_context
#define leonos_inputm_set_current_context reliefos_inputm_set_current_context
#define leonos_inputm_state reliefos_inputm_state
#define leonos_inputm_submit_key reliefos_inputm_submit_key
#define leonos_inputm_take_key reliefos_inputm_take_key
#define leonos_inputm_take_text reliefos_inputm_take_text
#define leonos_inputm_unregister reliefos_inputm_unregister
#endif /* LEONOS_API_H */
