/* Transitional compatibility forwarder (ReliefOS / ReliefNT rename).
 * Canonical declarations: <reliefos/license.h>.
 * No second layout definition exists behind these names. */
#ifndef LEONOS_LICENSE_H
#define LEONOS_LICENSE_H
#include <reliefos/license.h>

/* Old names alias the single canonical declaration. */
#define LEONOS_LICENSE_EMAIL_LEN RELIEFOS_LICENSE_EMAIL_LEN
#define LEONOS_LICENSE_INSTALL_ID_LEN RELIEFOS_LICENSE_INSTALL_ID_LEN
#define LEONOS_LICENSE_KEY_LEN RELIEFOS_LICENSE_KEY_LEN
#define LEONOS_LICENSE_SERVER_URL_LEN RELIEFOS_LICENSE_SERVER_URL_LEN
#define LEONOS_LICENSE_STATUS_CLOCK RELIEFOS_LICENSE_STATUS_CLOCK
#define LEONOS_LICENSE_STATUS_DENIED RELIEFOS_LICENSE_STATUS_DENIED
#define LEONOS_LICENSE_STATUS_INVALID RELIEFOS_LICENSE_STATUS_INVALID
#define LEONOS_LICENSE_STATUS_LEN RELIEFOS_LICENSE_STATUS_LEN
#define LEONOS_LICENSE_STATUS_MISSING RELIEFOS_LICENSE_STATUS_MISSING
#define LEONOS_LICENSE_STATUS_NETWORK RELIEFOS_LICENSE_STATUS_NETWORK
#define LEONOS_LICENSE_STATUS_OK RELIEFOS_LICENSE_STATUS_OK
#define leonos_license_activate_offline reliefos_license_activate_offline
#define leonos_license_activate_online reliefos_license_activate_online
#define leonos_license_default_server reliefos_license_default_server
#define leonos_license_info reliefos_license_info
#define leonos_license_install_id reliefos_license_install_id
#define leonos_license_required reliefos_license_required
#define leonos_license_status reliefos_license_status
#endif /* LEONOS_LICENSE_H */
