/* Transitional compatibility forwarder (ReliefOS / ReliefNT rename).
 * Canonical declarations: <reliefos/startup.h>.
 * No second layout definition exists behind these names. */
#ifndef LEONOS_STARTUP_H
#define LEONOS_STARTUP_H
#include <reliefos/startup.h>

/* Old names alias the single canonical declaration. */
#define LEONOS_STARTUP_ARG_LEN RELIEFOS_STARTUP_ARG_LEN
#define LEONOS_STARTUP_DECISION_ALLOW RELIEFOS_STARTUP_DECISION_ALLOW
#define LEONOS_STARTUP_DECISION_DENY RELIEFOS_STARTUP_DECISION_DENY
#define LEONOS_STARTUP_DECISION_DENY_REMEMBERED RELIEFOS_STARTUP_DECISION_DENY_REMEMBERED
#define LEONOS_STARTUP_MAX_ARGS RELIEFOS_STARTUP_MAX_ARGS
#define LEONOS_STARTUP_MAX_ENTRIES RELIEFOS_STARTUP_MAX_ENTRIES
#define LEONOS_STARTUP_STATUS_APPROVED RELIEFOS_STARTUP_STATUS_APPROVED
#define LEONOS_STARTUP_STATUS_CANCELLED RELIEFOS_STARTUP_STATUS_CANCELLED
#define LEONOS_STARTUP_STATUS_DENIED RELIEFOS_STARTUP_STATUS_DENIED
#define LEONOS_STARTUP_STATUS_DENIED_REMEMBERED RELIEFOS_STARTUP_STATUS_DENIED_REMEMBERED
#define LEONOS_STARTUP_STATUS_EXISTS RELIEFOS_STARTUP_STATUS_EXISTS
#define LEONOS_STARTUP_STATUS_FAILED RELIEFOS_STARTUP_STATUS_FAILED
#define LEONOS_STARTUP_STATUS_PENDING RELIEFOS_STARTUP_STATUS_PENDING
#define LEONOS_UAPI_STARTUP_ABI_H RELIEFOS_UAPI_STARTUP_ABI_H
#define leonos_startup_command reliefos_startup_command
#define leonos_startup_dialog_get reliefos_startup_dialog_get
#define leonos_startup_dialog_request reliefos_startup_dialog_request
#define leonos_startup_dialog_resolution reliefos_startup_dialog_resolution
#define leonos_startup_dialog_resolve reliefos_startup_dialog_resolve
#define leonos_startup_entry reliefos_startup_entry
#define leonos_startup_launch_current_user reliefos_startup_launch_current_user
#define leonos_startup_list reliefos_startup_list
#define leonos_startup_remove reliefos_startup_remove
#define leonos_startup_request reliefos_startup_request
#define leonos_startup_request_status reliefos_startup_request_status
#define leonos_startup_set_enabled reliefos_startup_set_enabled
#define leonos_startup_update reliefos_startup_update
#endif /* LEONOS_STARTUP_H */
